package infogui;
import java.io.File;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import ufrdriver.UFRDriver;
import java.util.Arrays;
import ufrcaller.uFrCaller;

/**
 * Zaccheus Everett
 * Tag Screen
 * Gives the user different ways to use/manipulate RFID Tags
 * 3/19/18
 * last edited 4/26/18
 */
public class TagScreen extends javax.swing.JFrame {
    //Constructors to other screens
    DataScreen DS = new DataScreen();
    CreditsScreen CS = new CreditsScreen();
    InstScreen IS = new InstScreen();
    PasswordScreen PS = new PasswordScreen();
    // variable declarations
    static Index test = new Index();
    ufrdriver.UFRDriver Main = new UFRDriver();
    javax.swing.JTextField[] txtBoxes = new javax.swing.JTextField[22];//Array that holds all text boxes
    String[] array = new String[22];
    static int[] defaultPass = new int[]{255,255,255,255,255,255};
    private String currentFile;//the chosen excel sheet
    
    private boolean openInst = true;//test if the instructions open at the start
    static boolean lock = false;// controls whether or not the tag is being locked
    // Creates new form AppUI 
    public TagScreen() {
        initComponents();
        setBoxes();
        instruct();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFileChooser1 = new javax.swing.JFileChooser();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        ReadButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        ClearButton1 = new javax.swing.JButton();
        UnlockButton = new javax.swing.JButton();
        LockButton = new javax.swing.JButton();
        changeTagPass = new javax.swing.JTextField();
        setReaderPass = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        readexcelbtn = new javax.swing.JButton();
        SetExcelFilebtn = new javax.swing.JButton();
        rowtxt = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        filelbl = new javax.swing.JLabel();
        DefaultPassbtn = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        FirstNameTxt = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        LastNameTxt = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        DepartmentTxt = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        CompNameTxt = new javax.swing.JTextField();
        jPanel10 = new javax.swing.JPanel();
        MakeTxt = new javax.swing.JTextField();
        jPanel11 = new javax.swing.JPanel();
        PassChangeTxt = new javax.swing.JTextField();
        jPanel12 = new javax.swing.JPanel();
        SerialNumTxt = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        PurchasedTxt = new javax.swing.JTextField();
        jPanel14 = new javax.swing.JPanel();
        PcLvTxt = new javax.swing.JTextField();
        jPanel15 = new javax.swing.JPanel();
        UsageTxt = new javax.swing.JTextField();
        jPanel16 = new javax.swing.JPanel();
        WarrantyTxt = new javax.swing.JTextField();
        jPanel17 = new javax.swing.JPanel();
        AgeTxt = new javax.swing.JTextField();
        jPanel18 = new javax.swing.JPanel();
        MacWTxt = new javax.swing.JTextField();
        jPanel19 = new javax.swing.JPanel();
        PhoneExtTxt = new javax.swing.JTextField();
        jPanel20 = new javax.swing.JPanel();
        PhoneTypeTxt = new javax.swing.JTextField();
        jPanel21 = new javax.swing.JPanel();
        MacWlessTxt = new javax.swing.JTextField();
        jPanel24 = new javax.swing.JPanel();
        ProjectorTxt = new javax.swing.JTextField();
        jPanel25 = new javax.swing.JPanel();
        ReimagedTxt = new javax.swing.JTextField();
        jPanel26 = new javax.swing.JPanel();
        LCDTxt = new javax.swing.JTextField();
        jPanel27 = new javax.swing.JPanel();
        AppleTxt = new javax.swing.JTextField();
        jPanel28 = new javax.swing.JPanel();
        NotesTxt = new javax.swing.JTextField();
        jPanel29 = new javax.swing.JPanel();
        PrinterTxt = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        CardUIDTxt = new javax.swing.JTextField();
        WriteButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        MenusMenu = new javax.swing.JMenu();
        dataMenuItem = new javax.swing.JMenuItem();
        HelpMenu = new javax.swing.JMenu();
        CreditsMenuItem = new javax.swing.JMenuItem();
        InstMenuItem = new javax.swing.JMenuItem();

        jFileChooser1.setDialogType(javax.swing.JFileChooser.CUSTOM_DIALOG);
        jFileChooser1.setApproveButtonText("select");
        jFileChooser1.setFileFilter(new excelFilter());

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Actions", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N
        jPanel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanel3.setName("Actions"); // NOI18N

        ReadButton.setText("Read Tag");
        ReadButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReadButtonActionPerformed(evt);
            }
        });

        jLabel1.setText("Reads information from RFID Tag");

        jLabel2.setText("Removes all information from Tag");

        ClearButton1.setText("Clear Tag");
        ClearButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearButton1ActionPerformed(evt);
            }
        });

        UnlockButton.setText("Change Tag Password");
        UnlockButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UnlockButtonActionPerformed(evt);
            }
        });

        LockButton.setText("Set Reader Password");
        LockButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LockButtonActionPerformed(evt);
            }
        });

        setReaderPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setReaderPassActionPerformed(evt);
            }
        });

        jLabel3.setText("Passwords must be between 1 and 6 characters");

        readexcelbtn.setText("Get Row From Excel");
        readexcelbtn.setToolTipText("");
        readexcelbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                readexcelbtnActionPerformed(evt);
            }
        });

        SetExcelFilebtn.setText("Set Excel File");
        SetExcelFilebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SetExcelFilebtnActionPerformed(evt);
            }
        });

        jLabel4.setText("Row:");

        filelbl.setText("Current File:");

        DefaultPassbtn.setText("Set Default Reader Password ");
        DefaultPassbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DefaultPassbtnActionPerformed(evt);
            }
        });

        jLabel6.setText("For new tags that have yet to have their passwords set");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(ReadButton)
                                .addGap(13, 13, 13))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addComponent(ClearButton1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(readexcelbtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rowtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(SetExcelFilebtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(filelbl)))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(UnlockButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(LockButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(changeTagPass)
                            .addComponent(setReaderPass)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(DefaultPassbtn)
                            .addComponent(jLabel6))
                        .addContainerGap())))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ReadButton)
                    .addComponent(jLabel1)
                    .addComponent(LockButton)
                    .addComponent(setReaderPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ClearButton1)
                    .addComponent(jLabel2)
                    .addComponent(UnlockButton)
                    .addComponent(changeTagPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(SetExcelFilebtn)
                            .addComponent(filelbl))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(readexcelbtn)
                            .addComponent(rowtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(DefaultPassbtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "First Name", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N

        FirstNameTxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        FirstNameTxt.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(FirstNameTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(FirstNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Last Name", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N

        LastNameTxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LastNameTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LastNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Department", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N

        DepartmentTxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(DepartmentTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(DepartmentTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Computer Name", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N

        CompNameTxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(CompNameTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(CompNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jPanel10.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Make/Model", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N

        MakeTxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MakeTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE)
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MakeTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jPanel11.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Last Password Change", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N

        PassChangeTxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PassChangeTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE)
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PassChangeTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jPanel12.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Serial Number", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N

        SerialNumTxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(SerialNumTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE)
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(SerialNumTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Date Purchased", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N

        PurchasedTxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PurchasedTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PurchasedTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jPanel14.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "PC Level (1-3)", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N

        PcLvTxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PcLvTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE)
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PcLvTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jPanel15.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Usage Scale (1 - 3)", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N

        UsageTxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(UsageTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE)
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(UsageTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jPanel16.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Warranty Status", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N

        WarrantyTxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        javax.swing.GroupLayout jPanel16Layout = new javax.swing.GroupLayout(jPanel16);
        jPanel16.setLayout(jPanel16Layout);
        jPanel16Layout.setHorizontalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(WarrantyTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE)
        );
        jPanel16Layout.setVerticalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(WarrantyTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jPanel17.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Age of the PC", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N

        AgeTxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        javax.swing.GroupLayout jPanel17Layout = new javax.swing.GroupLayout(jPanel17);
        jPanel17.setLayout(jPanel17Layout);
        jPanel17Layout.setHorizontalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(AgeTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE)
        );
        jPanel17Layout.setVerticalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(AgeTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jPanel18.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "MAC Address (Wired)", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N

        MacWTxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        javax.swing.GroupLayout jPanel18Layout = new javax.swing.GroupLayout(jPanel18);
        jPanel18.setLayout(jPanel18Layout);
        jPanel18Layout.setHorizontalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MacWTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE)
        );
        jPanel18Layout.setVerticalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MacWTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jPanel19.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Phone Extension", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N

        PhoneExtTxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        javax.swing.GroupLayout jPanel19Layout = new javax.swing.GroupLayout(jPanel19);
        jPanel19.setLayout(jPanel19Layout);
        jPanel19Layout.setHorizontalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PhoneExtTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE)
        );
        jPanel19Layout.setVerticalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PhoneExtTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jPanel20.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Phone Type (12 or 6 Buttons)", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 10))); // NOI18N

        PhoneTypeTxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        javax.swing.GroupLayout jPanel20Layout = new javax.swing.GroupLayout(jPanel20);
        jPanel20.setLayout(jPanel20Layout);
        jPanel20Layout.setHorizontalGroup(
            jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PhoneTypeTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE)
        );
        jPanel20Layout.setVerticalGroup(
            jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PhoneTypeTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jPanel21.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "MAC Address (Wireless)", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N

        MacWlessTxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        javax.swing.GroupLayout jPanel21Layout = new javax.swing.GroupLayout(jPanel21);
        jPanel21.setLayout(jPanel21Layout);
        jPanel21Layout.setHorizontalGroup(
            jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MacWlessTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE)
        );
        jPanel21Layout.setVerticalGroup(
            jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MacWlessTxt)
        );

        jPanel24.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Projector", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N

        ProjectorTxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        javax.swing.GroupLayout jPanel24Layout = new javax.swing.GroupLayout(jPanel24);
        jPanel24.setLayout(jPanel24Layout);
        jPanel24Layout.setHorizontalGroup(
            jPanel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ProjectorTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE)
        );
        jPanel24Layout.setVerticalGroup(
            jPanel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ProjectorTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jPanel25.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Re-Imaged", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N

        ReimagedTxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        javax.swing.GroupLayout jPanel25Layout = new javax.swing.GroupLayout(jPanel25);
        jPanel25.setLayout(jPanel25Layout);
        jPanel25Layout.setHorizontalGroup(
            jPanel25Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ReimagedTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE)
        );
        jPanel25Layout.setVerticalGroup(
            jPanel25Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ReimagedTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jPanel26.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "LCD TV", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N

        LCDTxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        javax.swing.GroupLayout jPanel26Layout = new javax.swing.GroupLayout(jPanel26);
        jPanel26.setLayout(jPanel26Layout);
        jPanel26Layout.setHorizontalGroup(
            jPanel26Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LCDTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE)
        );
        jPanel26Layout.setVerticalGroup(
            jPanel26Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LCDTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jPanel27.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Apple TV", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N

        AppleTxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        javax.swing.GroupLayout jPanel27Layout = new javax.swing.GroupLayout(jPanel27);
        jPanel27.setLayout(jPanel27Layout);
        jPanel27Layout.setHorizontalGroup(
            jPanel27Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(AppleTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE)
        );
        jPanel27Layout.setVerticalGroup(
            jPanel27Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(AppleTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jPanel28.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Notes", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N

        NotesTxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        javax.swing.GroupLayout jPanel28Layout = new javax.swing.GroupLayout(jPanel28);
        jPanel28.setLayout(jPanel28Layout);
        jPanel28Layout.setHorizontalGroup(
            jPanel28Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(NotesTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE)
        );
        jPanel28Layout.setVerticalGroup(
            jPanel28Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(NotesTxt)
        );

        jPanel29.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Printer", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N

        PrinterTxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        javax.swing.GroupLayout jPanel29Layout = new javax.swing.GroupLayout(jPanel29);
        jPanel29.setLayout(jPanel29Layout);
        jPanel29Layout.setHorizontalGroup(
            jPanel29Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PrinterTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE)
        );
        jPanel29Layout.setVerticalGroup(
            jPanel29Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PrinterTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jLabel8.setText("Card UID");

        CardUIDTxt.setEditable(false);

        WriteButton1.setText("Write to Tag");
        WriteButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WriteButton1ActionPerformed(evt);
            }
        });

        jLabel5.setText("Sends above Infomation to a Tag");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel27, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel9Layout.createSequentialGroup()
                                .addComponent(jPanel17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel9Layout.createSequentialGroup()
                                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel9Layout.createSequentialGroup()
                                .addComponent(jPanel21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel9Layout.createSequentialGroup()
                                .addComponent(jPanel24, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel25, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel9Layout.createSequentialGroup()
                                .addComponent(jPanel26, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel29, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(jPanel28, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel8)
                            .addComponent(WriteButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CardUIDTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))))
                .addGap(4, 4, 4))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel20, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel24, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel25, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel27, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel26, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel29, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel28, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(WriteButton1)
                            .addComponent(jLabel5))))
                .addGap(36, 36, 36)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CardUIDTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addContainerGap())
        );

        MenusMenu.setText("Menus");

        dataMenuItem.setText("Data");
        dataMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dataMenuItemActionPerformed(evt);
            }
        });
        MenusMenu.add(dataMenuItem);

        jMenuBar1.add(MenusMenu);

        HelpMenu.setText("Help");

        CreditsMenuItem.setText("Credits");
        CreditsMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreditsMenuItemActionPerformed(evt);
            }
        });
        HelpMenu.add(CreditsMenuItem);

        InstMenuItem.setText("Instructions");
        InstMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InstMenuItemActionPerformed(evt);
            }
        });
        HelpMenu.add(InstMenuItem);

        jMenuBar1.add(HelpMenu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

  
    //when the data tab is selected from the menu
    private void dataMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dataMenuItemActionPerformed
        // sets all the current text boxes into an array and passes it to the data screen - jacob
        String[] dataArray = new String[22];
        dataArray[0]=FirstNameTxt.getText();
        dataArray[1]=LastNameTxt.getText();
        dataArray[2]=CompNameTxt.getText();
        dataArray[3]=DepartmentTxt.getText();
        dataArray[4]=PassChangeTxt.getText();
        dataArray[5]=SerialNumTxt.getText();
        dataArray[6]=MakeTxt.getText();
        dataArray[7]=PurchasedTxt.getText();
        dataArray[8]=PcLvTxt.getText();
        dataArray[9]=UsageTxt.getText();
        dataArray[10]=AgeTxt.getText();
        dataArray[11]=WarrantyTxt.getText();
        dataArray[12]=MacWTxt.getText();
        dataArray[13]=MacWlessTxt.getText();
        dataArray[14]=PhoneTypeTxt.getText();
        dataArray[15]=PhoneExtTxt.getText();
        dataArray[16]=ProjectorTxt.getText();
        dataArray[17]=ReimagedTxt.getText();
        dataArray[18]=AppleTxt.getText();
        dataArray[19]=LCDTxt.getText();
        dataArray[20]=PrinterTxt.getText();
        dataArray[21]=NotesTxt.getText();
        
        DS.setScreen(dataArray);
        DS.show(true);//opens data screen
    }//GEN-LAST:event_dataMenuItemActionPerformed
  
    //when the credits tab is selected from the menu
    private void CreditsMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreditsMenuItemActionPerformed
        CS.show(true);//opens credits screen
    }//GEN-LAST:event_CreditsMenuItemActionPerformed
   
    //when the instructions tab is selected from the menu
    private void InstMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InstMenuItemActionPerformed
        IS.show(true);
    }//GEN-LAST:event_InstMenuItemActionPerformed

    //when the read Tag button is pressed
    private void ReadButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReadButtonActionPerformed
        reset();
                    // goes to main to get the card uid and sets it to text box -jacob
        String cardinfo;
         cardinfo = Main.getCardInfo();
         CardUIDTxt.setText(cardinfo);

         // array contains all of the data that was just read from the tag and sets it to each of its respective text boxes - jacob
        array = Main.ReadTag();
        FirstNameTxt.setText(array[0]);
        LastNameTxt.setText(array[1]);
        CompNameTxt.setText(array[2]);
        DepartmentTxt.setText(array[3]);
        PassChangeTxt.setText(array[4]);
        SerialNumTxt.setText(array[5]);
        MakeTxt.setText(array[6]);
        PurchasedTxt.setText(array[7]);
        PcLvTxt.setText(array[8]);
        UsageTxt.setText(array[9]);
        AgeTxt.setText(array[10]);
        WarrantyTxt.setText(array[11]);
        MacWTxt.setText(array[12]);
        MacWlessTxt.setText(array[13]);
        PhoneTypeTxt.setText(array[14]);
        PhoneExtTxt.setText(array[15]);
        ProjectorTxt.setText(array[16]);
        ReimagedTxt.setText(array[17]);
        AppleTxt.setText(array[18]);
        LCDTxt.setText(array[19]);
        PrinterTxt.setText(array[20]);
        NotesTxt.setText(array[21]);
    }//GEN-LAST:event_ReadButtonActionPerformed

    private void UnlockButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UnlockButtonActionPerformed
        try{
            // takes out the data that between each . in the set reader password txt box and then puts it into an array and passes it to main
            String readerkey; 
            readerkey = changeTagPass.getText();
            int[] keys = new int[6];
            if(readerkey.length() <= 6 & !readerkey.equals("")){
                while(readerkey.length() < 6){
                    readerkey += '0';
                }
             for(int x = 0; x < 6; x++){
      
                    keys[x] = (int)readerkey.charAt(x);
            }
             Main.SetTagKeys(keys);   
            }
            else {
                JOptionPane.showMessageDialog(null, "Invalid password: Password must be between 1 and 6 chracters inclusive, ", "InfoBox: " + "Password character(s) invalid!", JOptionPane.INFORMATION_MESSAGE);
            }
        }
        catch(Exception e){
             JOptionPane.showMessageDialog(null, "Invalid password: Password must be between 1 and 6 chracters inclusive, ", "InfoBox: " + "Password character(s) invalid!", JOptionPane.INFORMATION_MESSAGE);
        }
        
    }//GEN-LAST:event_UnlockButtonActionPerformed

    private void LockButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LockButtonActionPerformed
        try{
            // takes out the data that between each . in the set reader password txt box and then puts it into an array and passes it to main
            String readerkey; 
            readerkey = setReaderPass.getText();
            int[] keys = new int[6];
            if(readerkey.length() <= 6 & !readerkey.equals("")){
                while(readerkey.length() < 6){
                    readerkey += '0';
                }
             for(int x = 0; x < 6; x++){
      
                    keys[x] = (int)readerkey.charAt(x);
            }
             Main.SetReaderKeys(keys);   
            }
            else {
                JOptionPane.showMessageDialog(null, "Invalid password: Password must be between 1 and 6 chracters inclusive, ", "InfoBox: " + "Password character(s) invalid!", JOptionPane.INFORMATION_MESSAGE);
            }
        }
        catch(Exception e){
             JOptionPane.showMessageDialog(null, "Invalid password: Password must be between 1 and 6 chracters inclusive, ", "InfoBox: " + "Password character(s) invalid!", JOptionPane.INFORMATION_MESSAGE);
        }
        
    }//GEN-LAST:event_LockButtonActionPerformed

    private void WriteButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WriteButton1ActionPerformed

        
        String[] dataArray = new String[22];
         String cardinfo;
         cardinfo = Main.getCardInfo(); // gets the card uid
         CardUIDTxt.setText(cardinfo);
       
         // pulls all of the data out of the txt boxes and sends it to main to be written
        dataArray[0]=FirstNameTxt.getText().trim();
        dataArray[1]=LastNameTxt.getText().trim();
        dataArray[2]=CompNameTxt.getText().trim();
        dataArray[3]=DepartmentTxt.getText().trim();
        dataArray[4]=PassChangeTxt.getText().trim();
        dataArray[5]=SerialNumTxt.getText().trim();
        dataArray[6]=MakeTxt.getText().trim();
        dataArray[7]=PurchasedTxt.getText().trim();
        dataArray[8]=PcLvTxt.getText().trim();
        dataArray[9]=UsageTxt.getText().trim();
        dataArray[10]=AgeTxt.getText().trim();
        dataArray[11]=WarrantyTxt.getText().trim();
        dataArray[12]=MacWTxt.getText().trim();
        dataArray[13]=MacWlessTxt.getText().trim();
        dataArray[14]=PhoneTypeTxt.getText().trim();
        dataArray[15]=PhoneExtTxt.getText().trim();
        dataArray[16]=ProjectorTxt.getText().trim();
        dataArray[17]=ReimagedTxt.getText().trim();
        dataArray[18]=AppleTxt.getText().trim();
        dataArray[19]=LCDTxt.getText().trim();
        dataArray[20]=PrinterTxt.getText().trim();
        dataArray[21]=NotesTxt.getText().trim();
        
        
        Main.WriteToTag(dataArray);
    }//GEN-LAST:event_WriteButton1ActionPerformed

    private void ClearButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearButton1ActionPerformed
        // clear tag button sends thread to clear tag method in main 
        Main.clearTag();
    }//GEN-LAST:event_ClearButton1ActionPerformed

    private void setReaderPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setReaderPassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_setReaderPassActionPerformed

    private void readexcelbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_readexcelbtnActionPerformed
        // TODO add your handling code here:
        int row;
        String data;
        
        ArrayList<String> dataList = new ArrayList<>();
        data = rowtxt.getText();
        try{
            
            row = Integer.valueOf(data);
            if (row >=1){
                row -= 1;
            dataList = Main.readFromExcel(row,currentFile);
            FirstNameTxt.setText(dataList.get(0));
            LastNameTxt.setText(dataList.get(1));
            CompNameTxt.setText(dataList.get(2));
            DepartmentTxt.setText(dataList.get(3));
            PassChangeTxt.setText(dataList.get(4));
            SerialNumTxt.setText(dataList.get(5));
            MakeTxt.setText(dataList.get(6));
            PurchasedTxt.setText(dataList.get(7));
            PcLvTxt.setText(dataList.get(8));
            UsageTxt.setText(dataList.get(9));
            AgeTxt.setText(dataList.get(10));
            WarrantyTxt.setText(dataList.get(11));
            MacWTxt.setText(dataList.get(12));
            MacWlessTxt.setText(dataList.get(13));
            PhoneTypeTxt.setText(dataList.get(14));
            PhoneExtTxt.setText(dataList.get(15));
            ProjectorTxt.setText(dataList.get(16));
            ReimagedTxt.setText(dataList.get(17));
            AppleTxt.setText(dataList.get(18));
            LCDTxt.setText(dataList.get(19));
            PrinterTxt.setText(dataList.get(20));
            NotesTxt.setText(dataList.get(21));
            }
            else {
                 JOptionPane.showMessageDialog(null, "Row must be an a positive integer, ", "InfoBox: " + "Invalid row!", JOptionPane.INFORMATION_MESSAGE);
            }
        } 
        catch(Exception e){
             JOptionPane.showMessageDialog(null, "Row number must be a positive integer and the row must contain data, ", "InfoBox: " + "Invalid row!", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_readexcelbtnActionPerformed

    private void SetExcelFilebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SetExcelFilebtnActionPerformed
        fileChooser();
    }//GEN-LAST:event_SetExcelFilebtnActionPerformed

    private void DefaultPassbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DefaultPassbtnActionPerformed
        Main.SetReaderKeys(defaultPass);
    }//GEN-LAST:event_DefaultPassbtnActionPerformed
    private void fileChooser(){//lets the user select a file to send data to
        int returnVal = jFileChooser1.showDialog(this,"Select");//opens file chooser window
        if(returnVal == jFileChooser1.APPROVE_OPTION){//if the user presses open
            try{
                File file = jFileChooser1.getSelectedFile();
                currentFile = file.getAbsolutePath();//gets path of the file
                filelbl.setText(file.getName());//sets name of file
            }
            catch(Exception ex){System.out.println("Problem accessing file");}
        
        }
    }
    public void setCardUID(String text){
        //sets the card uid
        CardUIDTxt.setText(text);
    }        
   
    public void setText(String[] array){//Sets the text of all the textboxes on the screen
        for (int i = 0; i < txtBoxes.length; i++) {
            if(array[i] == null || array[i].equals("")) {txtBoxes[i].setText("");}
            else                                        {txtBoxes[i].setText(array[i]);}
        }
    }
        
    public void setText(String text){//Sets the text of all the textboxes on the screen
        for (int i = 0; i < txtBoxes.length; i++) {
                txtBoxes[i].setText(text);
        }
    }
    
   public String[] getInfo(){//gets data from text boxes on the screen and enters it into an array 
        String[] temp = new String[txtBoxes.length+1];//size for each textbox + the notes box
        for (int i = 0; i < txtBoxes.length; i++) {
            if (txtBoxes[i].getText()==null)    {temp[i]="";}//if the box is empty
 
            else                                {temp[i]=txtBoxes[i].getText();}
        }
        return temp;
    }
    
    
    private void reset(){//Clear the screen of text       
        setCardUID("");
        for (int i = 0; i < txtBoxes.length; i++) {
            txtBoxes[i].setText("");//if the box is empty
            
        }
    }
   
        
    private void instruct(){// opens instructions screen
        openInst=IS.getpref();//check if instructions are set to open on start 
        if(openInst==true){IS.show(true);}
        
    }
    
    private void setBoxes(){//sets Txtboxes into an array
        txtBoxes[0]=FirstNameTxt;
        txtBoxes[1]=LastNameTxt;
        txtBoxes[2]=CompNameTxt;
        txtBoxes[3]=DepartmentTxt;
        txtBoxes[4]=PassChangeTxt;
        txtBoxes[5]=SerialNumTxt;
        txtBoxes[6]=MakeTxt;
        txtBoxes[7]=PurchasedTxt;
        txtBoxes[8]=PcLvTxt;
        txtBoxes[9]=UsageTxt;
        txtBoxes[10]=AgeTxt;
        txtBoxes[11]=WarrantyTxt;
        txtBoxes[12]=MacWTxt;
        txtBoxes[13]=MacWlessTxt;
        txtBoxes[14]=PhoneTypeTxt;
        txtBoxes[15]=PhoneExtTxt;
        txtBoxes[16]=ProjectorTxt;
        txtBoxes[17]=ReimagedTxt;
        txtBoxes[18]=AppleTxt;
        txtBoxes[19]=LCDTxt;
        txtBoxes[20]=PrinterTxt;
        txtBoxes[21]=NotesTxt;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AgeTxt;
    private javax.swing.JTextField AppleTxt;
    private javax.swing.JTextField CardUIDTxt;
    private javax.swing.JButton ClearButton1;
    private javax.swing.JTextField CompNameTxt;
    private javax.swing.JMenuItem CreditsMenuItem;
    private javax.swing.JButton DefaultPassbtn;
    private javax.swing.JTextField DepartmentTxt;
    private javax.swing.JTextField FirstNameTxt;
    private javax.swing.JMenu HelpMenu;
    private javax.swing.JMenuItem InstMenuItem;
    private javax.swing.JTextField LCDTxt;
    private javax.swing.JTextField LastNameTxt;
    private javax.swing.JButton LockButton;
    private javax.swing.JTextField MacWTxt;
    private javax.swing.JTextField MacWlessTxt;
    private javax.swing.JTextField MakeTxt;
    private javax.swing.JMenu MenusMenu;
    private javax.swing.JTextField NotesTxt;
    private javax.swing.JTextField PassChangeTxt;
    private javax.swing.JTextField PcLvTxt;
    private javax.swing.JTextField PhoneExtTxt;
    private javax.swing.JTextField PhoneTypeTxt;
    private javax.swing.JTextField PrinterTxt;
    private javax.swing.JTextField ProjectorTxt;
    private javax.swing.JTextField PurchasedTxt;
    private javax.swing.JButton ReadButton;
    private javax.swing.JTextField ReimagedTxt;
    private javax.swing.JTextField SerialNumTxt;
    private javax.swing.JButton SetExcelFilebtn;
    private javax.swing.JButton UnlockButton;
    private javax.swing.JTextField UsageTxt;
    private javax.swing.JTextField WarrantyTxt;
    private javax.swing.JButton WriteButton1;
    private javax.swing.JTextField changeTagPass;
    private javax.swing.JMenuItem dataMenuItem;
    private javax.swing.JLabel filelbl;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel24;
    private javax.swing.JPanel jPanel25;
    private javax.swing.JPanel jPanel26;
    private javax.swing.JPanel jPanel27;
    private javax.swing.JPanel jPanel28;
    private javax.swing.JPanel jPanel29;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JButton readexcelbtn;
    private javax.swing.JTextField rowtxt;
    private javax.swing.JTextField setReaderPass;
    // End of variables declaration//GEN-END:variables
    class excelFilter extends javax.swing.filechooser.FileFilter {//filters out possible files
        private String[] extentions ={".xlsx",".xls",".xml",".csv" ,".ods" ,".ost"};//list file types
    
    @Override
    public boolean accept(File file){//checks for each extension in the array
    if (file.exists()){
        for (String ext : extentions){
            if(file.getName().toLowerCase().endsWith(ext))
            {return true;}
        }
    }
        return false;
    }
    @Override
    
    public String getDescription() {//shows the user the acceptable types of files

        // This description will be displayed in the dialog,
        // hard-coded = ugly, should be done via I18N
        return "Spreadsheets (*.xml/xlsx)";
        }
    }
}


